{
 "title": "PetClinic - Health View",
 "description": "Dashboard for Spring Boot2 Statistics(by micrometer-prometheus).\r\nThis is a fork of dashboard 6756, fixed for Spring Boot 2.3 and support for Jetty instead of Tomcat.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Customers Service (<<aws-region>>)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "application",
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_uptime_seconds{application=\"CustomersService\", region=\"<<aws-region>>\"}"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_sum{application=\"CustomersService\", region=\"<<aws-region>>\", exception=\"None\", uri=\"/prometheus\"}[15s]) / irate(http_server_requests_seconds_count{application=\"CustomersService\", region=\"<<aws-region>>\", exception=\"None\", uri=\"/prometheus\"}[15s])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
     "format": "dateTimeAsIso",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_start_time_seconds{application=\"CustomersService\", region=\"<<aws-region>>\"}*1000"
      }
     ]
    }
   ]
  },
  {
   "title": "Visits Service (us-east-1)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_uptime_seconds{application=\"VisitsService\", region=\"<<aws-region>>\"}"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_sum{application=\"VisitsService\", region=\"<<aws-region>>\", exception=\"None\", uri=\"/prometheus\"}[5m]) / irate(http_server_requests_seconds_count{application=\"VisitsService\", region=\"<<aws-region>>\", exception=\"None\", uri=\"/prometheus\"}[5m])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
     "format": "dateTimeAsIso",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_start_time_seconds{application=\"VisitsService\", region=\"<<aws-region>>\"}*1000"
      }
     ]
    }
   ]
  },
  {
   "title": "Vets Service (us-east-1)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_uptime_seconds{application=\"VetsService\", region=\"<<aws-region>>\"}"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_sum{application=\"VetsService\", region=\"<<aws-region>>\", exception=\"None\", uri=\"/prometheus\"}[5m]) / irate(http_server_requests_seconds_count{application=\"VetsService\", region=\"<<aws-region>>\", exception=\"None\", uri=\"/prometheus\"}[5m])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
     "format": "dateTimeAsIso",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_start_time_seconds{application=\"VetsService\", region=\"<<aws-region>>\"}*1000"
      }
     ]
    }
   ]
  },
  {
   "title": "PetCliniic UI (us-east-1)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_uptime_seconds{application=\"PetClinicUI\", region=\"<<aws-region>>\"}"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_sum{application=\"PetClinicUI\", region=\"<<aws-region>>\", exception=\"None\", uri=\"/prometheus\"}[5m]) / irate(http_server_requests_seconds_count{application=\"PetClinicUI\", region=\"<<aws-region>>\", exception=\"None\", uri=\"/prometheus\"}[5m])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
     "format": "dateTimeAsIso",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_start_time_seconds{application=\"PetClinicUI\", region=\"<<aws-region>>\"}*1000"
      }
     ]
    }
   ]
  }
 ]
}